### ISSUE TITLE
Error logging in console window

### ISSUE THREAD

**Issue by asirota** [asirota/watm#16]
If WATM encounters an error of some sort on a line, the console window should be used to log any errors

Potential errors/warnings to log:

- [watm error] line x : invalid function in function column
- [watm error] line x : query column style or ID missing for function
- [watm error] line x : invalid style or ID format
- [watm error] WATM configuration file not found
- [watm error] WATM configuration file is not in correct format
- [watm notice] switched to alternate language

There may be other errors/notices  to log which will help people debugging WATM configuration.

Also good to have a JS variable in WATM installation script to turn on error logging/turn off error logging

**Comment by priscila-gomes** [comment]
In the **Global Javascript** from **Admin** just have to add below line for turning on or off error logging.

var turnOnErrorLogging = false; 

All error or notice will be shown based on this variable. function log(text) is used to show all log messages. Changed format of showing error or notice. Every error message will start with [watm error].... and notice with [watm notice].

**Comment by asirota** [comment]
Sounds good -- please add a pull request with your changes so I can review. I have added you @priscila-gomes as a contributor to this repository.

**Comment by asirota** [comment]
@priscila-gomes I reviewed your PR -- it doesn't look like you addressed all the issues in this issue but only looked at existing error messages. I am sorry but I don't think we will move ahead.
